#!/usr/bin/env python3
# Copyright (C) 2026, Stolo Systems Inc. GPL-3.0-or-later; see LICENSE.
"""Reproduce GraphicsStolo.h: a compact five-row pixel face, source strings, MSB-first rows.

No imaging dependencies. --check detects stale output; --preview DIR writes
PBM contact sheets at native resolution (software review, not device evidence).
"""
import argparse
from pathlib import Path

# Each slash-separated row is a literal pixel row (mostly 3x5). Narrow glyphs save room
# for the factual attribution at 64 px; lowercase uses the same pixel face.
FONT = dict(zip('ABCDEFGHIJKLMNOPQRSTUVWXYZ', [
    '010/101/111/101/101', '110/101/110/101/110', '011/100/100/100/011',
    '110/101/101/101/110', '111/100/110/100/111', '111/100/110/100/100',
    '011/100/101/101/011', '101/101/111/101/101', '1/1/1/1/1',
    '001/001/001/101/010', '101/101/110/101/101', '100/100/100/100/111',
    '10001/11011/10101/10001/10001', '1001/1101/1011/1001/1001', '010/101/101/101/010',
    '110/101/110/100/100', '010/101/101/111/011', '110/101/110/101/101',
    '011/100/010/001/110', '111/010/010/010/010', '101/101/101/101/111',
    '101/101/101/101/010', '10001/10001/10101/10101/01010', '101/101/010/101/101',
    '101/101/010/010/010', '111/001/010/100/111',
]))
FONT.update(dict(zip('0123456789', [
    '111/101/101/101/111', '010/110/010/010/111', '110/001/010/100/111',
    '110/001/010/001/110', '101/101/111/001/001', '111/100/110/001/110',
    '011/100/111/101/111', '111/001/010/010/010', '111/101/111/101/111',
    '111/101/111/001/110',
])))
FONT.update({' ': '00/00/00/00/00', '.': '0/0/0/0/1', '·': '0/0/1/0/0'})

# name: (height, [(text, top row, integer scale), ...]). Boot attribution
# is one factual notice wrapped onto two lines, with no compatibility claim.
ART = {
    'bm_def': (37, [('STOLO', 1, 2), ('NODE', 14, 1)]),
    'bm_def_lc': (37, [('STOLO', 1, 2), ('NODE', 14, 1)]),
    'bm_boot': (27, [('STOLO NODE', 0, 1), ('STARTING', 7, 1),
                    ('RNode firmware', 15, 1), ('unsigned.io GPLv3', 22, 1)]),
    'bm_pairing': (27, [('PAIRING', 4, 1)]),
    'bm_stolo_enroll': (27, [('ENROLL WINDOW', 4, 1)]),
    'bm_stolo_rescue': (27, [('RESCUE', 4, 1)]),
    'bm_stolo_identity': (27, [('NEW IDENTITY', 10, 1)]),
    'bm_stolo_store_error': (27, [('STORE ERROR', 2, 1), ('HOLD BTN', 11, 1), ('AT BOOT', 20, 1)]),
}


def draw(canvas, text, top, scale=1):
    glyphs = [FONT[c.upper()].split('/') for c in text]
    width = (sum(len(g[0]) for g in glyphs) + len(glyphs) - 1) * scale
    assert width <= len(canvas[0]), (text, width)
    assert top + 5 * scale <= len(canvas), text
    left = (len(canvas[0]) - width) // 2
    for glyph in glyphs:
        for y, row in enumerate(glyph):
            for x, pixel in enumerate(row):
                for dy in range(scale):
                    for dx in range(scale):
                        canvas[top + y*scale + dy][left + x*scale + dx] = int(pixel)
        left += (len(glyph[0]) + 1) * scale


def bitmaps():
    result = {}
    for name, (height, lines) in ART.items():
        canvas = [[0]*64 for _ in range(height)]
        for text, top, scale in lines:
            draw(canvas, text, top, scale)
        result[name] = canvas
    # Ten independent 8x5 glyphs, indexed by digit*5 in the renderer.
    result['bm_stolo_digits'] = []
    for digit in '0123456789':
        canvas = [[0]*8 for _ in range(5)]
        draw(canvas, digit, 0)
        result['bm_stolo_digits'].extend(canvas)
    return result


def generate(images):
    output = ['// Copyright (C) 2026, Stolo Systems Inc. GPL-3.0-or-later; see LICENSE.',
              '// Generated by Tools/oled_bitmaps.py. Edit the font/strings there, never hex here.', '#pragma once', '']
    for name, canvas in images.items():
        data = [sum(row[x+i] << (7-i) for i in range(8))
                for row in canvas for x in range(0, len(row), 8)]
        output.append(f'const unsigned char {name}[] PROGMEM = {{')
        for i in range(0, len(data), 16):
            output.append('  ' + ', '.join(f'0x{b:02x}' for b in data[i:i+16]) + ',')
        output.extend(['};', ''])
    return '\n'.join(output)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--preview', type=Path)
    args = parser.parse_args()
    images = bitmaps()
    target = Path(__file__).resolve().parents[1] / 'GraphicsStolo.h'
    generated = generate(images)
    if args.check:
        if not target.exists() or target.read_text() != generated:
            raise SystemExit('GraphicsStolo.h is stale; run python3 Tools/oled_bitmaps.py')
    else:
        target.write_text(generated)
    if args.preview:
        args.preview.mkdir(parents=True, exist_ok=True)
        for name, canvas in images.items():
            (args.preview / (name + '.pbm')).write_text(
                f'P1\n{len(canvas[0])} {len(canvas)}\n' + '\n'.join(' '.join(map(str, row)) for row in canvas))


if __name__ == '__main__':
    main()
